### ISSUE TITLE
Unable to compile flash3kyuu_deband

### ISSUE THREAD

**Issue by TurboCheetah** [4re/vapoursynth-portage#111]
From what I've seen when trying to find a solution, this seems to be an issue of using python3 as opposed to python2.

```python
Waf: The wscript in '/var/tmp/portage/media-plugins/vapoursynth-flash3kyuu_deband-2.0.0.20180808/work/vapoursynth-flash3kyuu_deband-2.0.0.20180808' is unreadable
Traceback (most recent call last):
  File "/var/tmp/portage/media-plugins/vapoursynth-flash3kyuu_deband-2.0.0.20180808/work/vapoursynth-flash3kyuu_deband-2.0.0.20180808/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/var/tmp/portage/media-plugins/vapoursynth-flash3kyuu_deband-2.0.0.20180808/work/vapoursynth-flash3kyuu_deband-2.0.0.20180808/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/media-plugins/vapoursynth-flash3kyuu_deband-2.0.0.20180808/work/vapoursynth-flash3kyuu_deband-2.0.0.20180808/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Context.py", line 349, in load_module
    code=Utils.readf(path,m='rU',encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/media-plugins/vapoursynth-flash3kyuu_deband-2.0.0.20180808/work/vapoursynth-flash3kyuu_deband-2.0.0.20180808/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Utils.py", line 141, in readf
    with open(fname,m)as f:
         ^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'
```

**Comment by 4re** [comment]
Thx for the report, it should properly compile now.
